@extends('layouts.admin')
@section('title', 'Reports')
@section('page-title', 'Reports')
@section('page-description', 'Operational insights and portable CSV exports')
@section('content')
<div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
    <div class="panel p-5"><p class="text-sm font-semibold text-slate-500">Transactions this month</p><p class="mt-2 text-3xl font-black">{{ number_format($monthlyTransactionCount) }}</p></div>
    <div class="flex flex-wrap gap-3"><a href="{{ route('admin.reports.books.export') }}" class="btn-secondary">Export books CSV</a><a href="{{ route('admin.reports.transactions.export') }}" class="btn-primary">Export transactions CSV</a></div>
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-2">
    <section class="panel overflow-hidden"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-bold">Most borrowed books</h2></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse ($topBooks as $book)<div class="flex items-center justify-between p-5"><div><p class="font-semibold">{{ $book->title }}</p><p class="text-xs text-slate-500">{{ $book->author }}</p></div><span class="text-sm font-black text-indigo-600">{{ $book->borrow_count }} loans</span></div>@empty<p class="p-5 text-sm text-slate-500">No borrowing data.</p>@endforelse</div></section>
    <section class="panel overflow-hidden"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-bold">Most active members</h2></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse ($activeMembers as $member)<a href="{{ route('admin.members.show', $member) }}" class="flex items-center justify-between p-5 hover:bg-slate-50 dark:hover:bg-slate-800"><div><p class="font-semibold">{{ $member->full_name }}</p><p class="text-xs text-slate-500">{{ $member->member_code }}</p></div><span class="text-sm font-black text-emerald-600">{{ $member->transaction_count }} loans</span></a>@empty<p class="p-5 text-sm text-slate-500">No member activity.</p>@endforelse</div></section>
    <section class="panel overflow-hidden"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-bold">Currently borrowed</h2></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse ($borrowedBooks as $transaction)<a href="{{ route('admin.transactions.show', $transaction) }}" class="flex items-center justify-between gap-4 p-5 hover:bg-slate-50 dark:hover:bg-slate-800"><div><p class="font-semibold">{{ $transaction->bookCopy->book->title }}</p><p class="text-xs text-slate-500">{{ $transaction->member->full_name }} · due {{ $transaction->due_at->format('d M') }}</p></div><x-badge :status="$transaction->display_status" /></a>@empty<p class="p-5 text-sm text-slate-500">No active loans.</p>@endforelse</div></section>
    <section class="panel overflow-hidden"><div class="border-b border-slate-200 p-5 dark:border-slate-800"><h2 class="font-bold">Overdue books</h2></div><div class="divide-y divide-slate-100 dark:divide-slate-800">@forelse ($overdueBooks as $transaction)<a href="{{ route('admin.transactions.show', $transaction) }}" class="flex items-center justify-between gap-4 p-5 hover:bg-slate-50 dark:hover:bg-slate-800"><div><p class="font-semibold">{{ $transaction->bookCopy->book->title }}</p><p class="text-xs text-slate-500">{{ $transaction->member->full_name }}</p></div><span class="text-sm font-black text-red-600">{{ $transaction->days_overdue }} days</span></a>@empty<p class="p-5 text-sm text-slate-500">No overdue loans.</p>@endforelse</div></section>
</div>
@endsection
